### ISSUE TITLE
Obtaining unweighted frequencies with crosstab()

### ISSUE THREAD

**Issue by zilinskyjan** [jdjohn215/pollster#1]
John, apologies if I missed this, but it looks like `crosstab(...,n=TRUE)` only reports weighted frequencies? (Or can a table containing unweighted N be produced?)

I realize that unweighted N can be obtained with `pollster::summary_table()` or `janitor::tabyl()` or other methods, it just seems it could be useful to show raw frequencies in crosstabs. 

Thanks!

**Comment by jdjohn215** [comment]
Hi Jan,

Thanks for the recommendation. I really should've included this option already. I'll add an option like this `crosstab(..., n=TRUE, unwt_n = TRUE)`. The default value will be `unwt_n = FALSE` so that the default behavior doesn't change. Does that seem sensible to you?

**Comment by zilinskyjan** [comment]
Thank you very much, John. The enhancement as you described it would be terrific.

**Comment by jdjohn215** [comment]
I've added this as an option to all the crosstab functions. As it turns out, the CRAN package submission team is on vacation until August 24th. I'll submit the update once they're back. In the meantime, you can access the new features by downloading the development version. I welcome any feedback you might have.

**Comment by zilinskyjan** [comment]
Really appreciate that you added this feature, thank you John!
